feat: implement `Sticker` object
retuxteam/retux pull request #21
Opened 2022-07-29 19:47 UTC by Dworv

This PR implements the Discord `Sticker` object as well as needed dependencies. It also implements stickers to the `guild.py` and `channel.py` files.

2022-07-30 15:19 UTC, i0bs requested changes
There is inconsistency between when you're setting a `None` default. Additionally, kwargs-only dataclasses use the `kw_only` kwarg.

2022-07-30 15:19 UTC, i0bs commented on retux/client/resources/channel.py
> +    sticker_items: list[dict] | list[StickerItem] | None = field(converter=optional_c(list_c(StickerItem)))
```suggestion
    sticker_items: list[dict] | list[StickerItem] | None = field(converter=optional_c(list_c(StickerItem)), default=None)
```

2022-07-30 15:19 UTC, i0bs commented on retux/client/resources/channel.py
> +    sticker_items: list[dict] | list[StickerItem] | None = field(converter=optional_c(list_c(StickerItem)))
Let's add a property method for this, similar to what we have in `WelcomeScreen`. `items` should be good enough.

2022-07-30 15:19 UTC, i0bs commented on retux/client/resources/channel.py
> +    stickers: list[dict] | list[Sticker] | None = field(converter=optional_c(list_c(Sticker)))
```suggestion
    stickers: list[dict] | list[Sticker] | None = field(converter=optional_c(list_c(Sticker)), default=None)
```

2022-07-30 15:19 UTC, i0bs commented on retux/client/resources/sticker.py
> +    available: bool | None = field(default=None)
```suggestion
    available: bool = field(default=True)
```

I believe reading from the docs they're imposing optional as in identity and not value relation. If the documentation from their website is proper, then I presume it's.. `True` by default?

2022-07-30 15:19 UTC, i0bs commented on retux/client/resources/sticker.py
> +    guild_id: str | Snowflake | None = field(converter=optional_c(Snowflake))
```suggestion
    guild_id: str | Snowflake | None = field(converter=optional_c(Snowflake), default=None)
```

2022-07-30 15:19 UTC, i0bs commented on retux/client/resources/sticker.py
> +@define(kwargs_only=True)
```suggestion
@define(kw_only=True)
```

2022-07-30 15:19 UTC, i0bs commented on retux/client/resources/sticker.py
> +@define(kwargs_only=True)
```suggestion
@define(kw_only=True)
```

2022-07-30 15:19 UTC, i0bs commented on retux/client/resources/sticker.py
> +    banner_asset_id: str | Snowflake | None = field(converter=optional_c(Snowflake))
```suggestion
    banner_asset_id: str | Snowflake | None = field(converter=optional_c(Snowflake), default=None)
```

2022-07-30 16:09 UTC, Dworv commented on retux/client/resources/channel.py
> +    sticker_items: list[dict] | list[StickerItem] | None = field(converter=optional_c(list_c(StickerItem)))
Got it.

2022-07-30 16:13 UTC, Dworv commented on retux/client/resources/channel.py
> +    sticker_items: list[dict] | list[StickerItem] | None = field(converter=optional_c(list_c(StickerItem)))
On second thought, `StickerItem`s aren't actually very useful, so I don't think this will be necessary.

2022-07-30 16:57 UTC, i0bs commented on retux/client/resources/channel.py
> +    sticker_items: list[dict] | list[StickerItem] | None = field(converter=optional_c(list_c(StickerItem)))
Yeah I'll agree, this can be resolved.

2022-07-31 19:52 UTC, i0bs reviewed
Everything looks good for documentation and fields, just got some notes down

2022-07-31 19:52 UTC, i0bs commented on retux/client/resources/channel.py
>      """# The components on a message."""
You've.. docstring'd a comment? 🤨

2022-07-31 19:52 UTC, i0bs commented on retux/client/resources/sticker.py
> +    tags: str = field()
This is so weird reading it from documentation. It's a string but represents the client rendering of autocompleted results when typing words in the chatbar. The tags themselves can be a string literal `"name, name2, name3"` and soforth.

We could maybe create a property method `clean_tags` where we properly split them up. How would you feel about this?

2022-08-01 00:58 UTC, Dworv commented on retux/client/resources/sticker.py
> +    tags: str = field()
Well this can either be a list or the name of an emoji, but sure that sounds like possibly a good idea.

2022-08-01 00:59 UTC, Dworv commented on retux/client/resources/channel.py
>      """# The components on a message."""
Whoops

2022-08-01 01:00 UTC, Dworv commented on retux/client/resources/sticker.py
> +    tags: str = field()
Maybe also a property method to turn it into an emoji object?

2022-08-01 01:02 UTC, Dworv commented on retux/client/resources/channel.py
>      """# The components on a message."""
Wait this wasn't in my PR was it?

2022-08-01 01:05 UTC, i0bs commented on retux/client/resources/channel.py
>      """# The components on a message."""
It was in a previous PR of yours, figure that now I've noticed it we could correct it lol

2022-08-01 01:05 UTC, i0bs commented on retux/client/resources/sticker.py
> +    tags: str = field()
Yeah, a `to_emoji` would be beneficial as well here.

2022-08-01 08:09 UTC, i0bs commented on retux/client/resources/sticker.py
> +    tags: str = field()
Carrying over from the Discord, but the decision was made on this to just provide a `clean_tags` property method to produce a nicely sanitised version of the `tags` attribute as a list of tags.

2022-08-01 20:39 UTC, i0bs requested changes
correct L2007

2022-08-01 20:50 UTC, Dworv commented
> correct L2007

Sorry what?

2022-08-01 21:11 UTC, i0bs submitted a review, later dismissed
LGTM, thank you for contributing to retux!

2022-08-01 21:12 UTC, i0bs approved these changes
fucking github stale ass shit

2022-08-01 21:12 UTC, merged