feat: implement `image` object
retuxteam/retux pull request #23
Opened 2022-07-30 17:19 UTC by EdVraz

This PR implements the `Image` object

2022-07-31 20:02 UTC, i0bs reviewed
Excerpt from a review comment on #4 

![image](https://user-images.githubusercontent.com/41456914/182042969-4020759e-4587-4884-aa5f-49a1babe008b.png)

I really like the idea of an `Image` object for abstraction with what this library plans to achieve. The one thing I think this object should consider accomplishing is to either purely be an ABC (see locating this code into the `resources/abc.py` file) that only stores abstracted content of an image, e.g. `width`, `height`, etc. or an ABC that allows both storing *and* creating imagedata for Discord.

I do welcome and encourage any contributors of retux so far to openly communicate and share their thoughts on this. In my opinion, I believe the best one would be the first: an ABC only to store data. This way, we can disassociate `Image` being on-par to `File`. If we were to introduce further mixins into our library, the doctrine would more so become "build ABCs that allow higher extrapolation of builder methods."

I will not make any review until there's been a mutual consensus or compromise met.

2022-07-31 20:16 UTC, EdVraz commented
> Excerpt from a review comment on #4 
> 
> ![image](https://user-images.githubusercontent.com/41456914/182042969-4020759e-4587-4884-aa5f-49a1babe008b.png)
> 
> I really like the idea of an `Image` object for abstraction with what this library plans to achieve. The one thing I think this object should consider accomplishing is to either purely be an ABC (see locating this code into the `resources/abc.py` file) that only stores abstracted content of an image, e.g. `width`, `height`, etc. or an ABC that allows both storing *and* creating imagedata for Discord.
> 
> I do welcome and encourage any contributors of retux so far to openly communicate and share their thoughts on this. In my opinion, I believe the best one would be the first: an ABC only to store data. This way, we can disassociate `Image` being on-par to `File`. If we were to introduce further mixins into our library, the doctrine would more so become "build ABCs that allow higher extrapolation of builder methods."
> 
> I will not make any review until there's been a mutual consensus or compromise met.

Oh I see, I'll try that tomorrow

2022-08-05 06:34 UTC, Dworv commented
Having a converter to an `Image` class and then giving that a `.hash` attribute sounds like the best option.

2022-08-05 17:08 UTC, EdVraz commented
Reopening and modifying to only cover `ImageData` to upload data to discord's backend

2022-08-05 17:26 UTC, Dworv requested changes
Implement __repr__

2022-08-05 17:26 UTC, Dworv commented on retux/client/resources/misc.py
> +
You should probably implement a `__repr__` similar to how `Snowflake` works so that its easy for us to send it to Discord. This isn't actually meant to be a dictionary sent to Discord, its supposed to be a single string, just like a `Snowflake`.

2022-08-05 17:27 UTC, EdVraz commented on retux/client/resources/misc.py
> +
Good idea, will do

2022-08-05 17:29 UTC, Dworv commented on retux/client/resources/misc.py
> +
LGTM, you can mark this as done or whatever.

2022-08-08 13:19 UTC, i0bs requested changes
The removal of an underscore was explained to me by Bluenix. Essentially nothing should need to be underscored more than once for private level accessibility unless we really *really* **really** don't want anyone to touch or see it. In most cases it's apparently unnecessary.

2022-08-08 13:19 UTC, i0bs commented on retux/client/resources/misc.py
> +    __data: str = field(default=None)
```suggestion
    _data: str = field(default=None)
```

2022-08-08 13:19 UTC, i0bs commented on retux/client/resources/misc.py
> +        return f"data:image/{self.type};base64,{self.__data}"
```suggestion
        return f"data:image/{self.type};base64,{self._data}"
```

2022-08-10 12:29 UTC, i0bs approved these changes
LGTM, thank you for contributing to retux!

2022-08-10 12:29 UTC, merged