feat: Implement mixins
retuxteam/retux pull request #25
Opened 2022-07-30 20:00 UTC by EdVraz

This PR aims to implement important mixnins

draft until I made the docs

2022-07-31 19:00 UTC, EdVraz commented
added docs, this is ready for review @i0bs

2022-07-31 20:24 UTC, i0bs requested changes
I don't know if PyCharm is being weird to you, but this just reflects some corrections on docstring styles.

Also, as a side note, I've realised that it may be a little inefficient for us to throw every single mixin into a separate file. It's probably great for organisation purposes, but now that I look at it, I can't imagine us building mixins to go into mixins for instance. Maybe we should move them into just a `mixins.py`?

Anywho, first revision of changes requested.

2022-07-31 20:24 UTC, i0bs commented on retux/client/mixins/controllable.py
> +    _______
```suggestion
    -------
```

2022-07-31 20:24 UTC, i0bs commented on retux/client/mixins/controllable.py
> +        ___________
```suggestion
        ----------
```

2022-07-31 20:24 UTC, i0bs commented on retux/client/mixins/controllable.py
> +        _______
```suggestion
        -------
```

2022-07-31 20:24 UTC, i0bs commented on retux/client/mixins/controllable.py
> +            The data Discord returned as dict.
```suggestion
            The data of the object returned by Discord.
```

2022-07-31 20:24 UTC, i0bs commented on retux/client/mixins/controllable.py
> +        __________
```suggestion
        ----------
```

2022-07-31 20:24 UTC, i0bs commented on retux/client/mixins/controllable.py
> +        _______
```suggestion
        -------
```

2022-07-31 20:24 UTC, i0bs commented on retux/client/mixins/controllable.py
> +            The data Discord returned as dict.
```suggestion
            The data of the object returned by Discord.
```

2022-07-31 20:24 UTC, i0bs commented on retux/client/mixins/editable.py
> +    _______
```suggestion
    -------
```

2022-07-31 20:24 UTC, i0bs commented on retux/client/mixins/editable.py
> +        __________
```suggestion
        ----------
```

2022-07-31 20:24 UTC, i0bs commented on retux/client/mixins/editable.py
> +        _______
```suggestion
        -------
```

2022-07-31 20:24 UTC, i0bs commented on retux/client/mixins/editable.py
> +        """Alias of `edit()`"""
```suggestion
        """An alias of the `edit()` method."""
```

2022-07-31 20:24 UTC, i0bs commented on retux/client/mixins/editable.py
> +        """
This method is documented in the class' docstring but lacks the documentation in the method itself.

```suggestion
        """
        Edits an object with the given path and kwargs.

```

2022-07-31 20:24 UTC, i0bs commented on retux/client/mixins/editable.py
> +            The data to edit
```suggestion
            The data to edit.
```

2022-07-31 20:24 UTC, i0bs commented on retux/client/mixins/editable.py
> +        __________
```suggestion
        ----------
```

2022-07-31 20:24 UTC, i0bs commented on retux/client/mixins/editable.py
> +        _______
```suggestion
        -------
```

2022-07-31 20:24 UTC, i0bs commented on retux/client/mixins/respondable.py
> +    _______
```suggestion
    -------
```

2022-07-31 20:24 UTC, i0bs commented on retux/client/mixins/respondable.py
> +    A mixin for objects with send/edit/delete methods
```suggestion
    A mixin for objects with send/edit/delete methods.
```

2022-07-31 20:24 UTC, i0bs commented on retux/client/mixins/respondable.py
> +        An alias of `respond()`
```suggestion
        An alias of the `respond()` method.
```

2022-07-31 20:24 UTC, i0bs commented on retux/client/mixins/respondable.py
> +        Executes a `respond` action to discord with the given Route and keyword arguments.
I get what's being meant here but I'm lost what the "respond action" is. Did you mean "Executes a `Create Interaction Response` action" ?

```suggestion
        Executes a `respond` action to Discord with the given route and keyword arguments.
```

2022-07-31 20:24 UTC, i0bs commented on retux/client/mixins/respondable.py
> +        __________
```suggestion
        ----------
```

2022-07-31 20:24 UTC, i0bs commented on retux/client/mixins/respondable.py
> +        _______
```suggestion
        -------
```

2022-07-31 20:24 UTC, i0bs commented on retux/client/mixins/respondable.py
> +            The data Discord returned as dict.
```suggestion
            The data of the interaction response returned by Discord.
```

2022-07-31 20:24 UTC, i0bs commented on retux/client/mixins/respondable.py
> +        Executes a `respond` action to discord with the given Route and keyword arguments.
See review comment left on the `respond()` method's docstring.

2022-07-31 20:24 UTC, i0bs commented on retux/client/mixins/respondable.py
> +        """Alias of `respond()`"""
```suggestion
        """An alias of the `respond()` method."""
```

2022-08-01 20:53 UTC, i0bs approved these changes
LGTM, thank you for contributing to retux!

2022-08-01 20:53 UTC, merged