feat: implement the `Invite` object
retuxteam/retux pull request #27
Opened 2022-07-31 19:56 UTC by EdVraz

This PR aims to implement the `Invite` object

resolves #23

2022-08-01 00:53 UTC, i0bs requested changes

2022-08-01 00:53 UTC, i0bs commented on retux/client/resources/invite.py
> +    Represents an InviteStageInstance from Discord. This is deprecated.
```suggestion
    Represents an invite to a stage instance from Discord. This is deprecated.
```

2022-08-01 00:53 UTC, i0bs commented on retux/client/resources/invite.py
> +    Represents an Invite from Discord
```suggestion
    Represents an invite from Discord.
```

2022-08-01 00:53 UTC, i0bs commented on retux/client/resources/invite.py
> +        Approximate count of online members, returned from the `GET /invites/<code>` endpoint when `with_counts=True`.
```suggestion
        Approximate count of online members, returned from the `Get Invites` endpoint
        when `with_counts=True`.
```

2022-08-01 00:53 UTC, i0bs commented on retux/client/resources/invite.py
> +        Approximate count of total members, returned from the `GET /invites/<code>` endpoint when `with_counts=True`.
```suggestion
        Approximate count of total members, returned from the `Get Invites` endpoint
        when `with_counts=True`.
```

2022-08-01 00:53 UTC, i0bs commented on retux/client/resources/invite.py
> +        The expiration date of this invite, returned from the `GET /invites/<code>` endpoint when `with_expiration=True`.
```suggestion
        The expiration date of this invite, returned from the `Get Invites` endpoint
        when `with_expiration=True`.
```

2022-08-01 00:53 UTC, i0bs commented on retux/client/resources/invite.py
> +    """Approximate count of online members, returned from the `GET /invites/<code>` endpoint when `with_counts=True`."""
```suggestion
    """Approximate count of online members, returned from the `Get Invites` endpoint when `with_counts=True`."""
```

2022-08-01 00:53 UTC, i0bs commented on retux/client/resources/invite.py
> +    """Approximate count of total members, returned from the `GET /invites/<code>` endpoint when `with_counts=True`."""
```suggestion
    """Approximate count of total members, returned from the `Get Invites` endpoint when `with_counts=True`."""
```

2022-08-01 00:53 UTC, i0bs commented on retux/client/resources/invite.py
> +    expires_at: datetime | None = field(converter=optional_c(datetime.fromisoformat), default=None)
```suggestion
    expires_at: str | datetime | None = field(converter=optional_c(datetime.fromisoformat), default=None)
```

2022-08-01 00:53 UTC, i0bs commented on retux/client/resources/invite.py
> +    target_application: Application | None = field(converter=optional_c(Application), default=None)
```suggestion
    target_application: dict | Application | None = field(converter=optional_c(Application), default=None)
```

2022-08-01 00:53 UTC, i0bs commented on retux/client/resources/invite.py
> +    guild: Guild | None = field(converter=optional_c(Guild), default=None)
```suggestion
    guild: dict | Guild | None = field(converter=optional_c(Guild), default=None)
```

2022-08-01 00:53 UTC, i0bs commented on retux/client/resources/invite.py
> +    channel: Channel | None = field(converter=optional_c(Channel), default=None)
```suggestion
    channel: dict | Channel | None = field(converter=optional_c(Channel), default=None)
```

2022-08-01 00:53 UTC, i0bs commented on retux/client/resources/invite.py
> +    inviter: User | None = field(converter=optional_c(User), default=None)
```suggestion
    inviter: dict | User | None = field(converter=optional_c(User), default=None)
```

2022-08-01 00:53 UTC, i0bs commented on retux/client/resources/invite.py
> +    target_user: User | None = field(converter=optional_c(User), default=None)
```suggestion
    target_user: dict | User | None = field(converter=optional_c(User), default=None)
```

2022-08-01 00:53 UTC, i0bs commented on retux/client/resources/invite.py
> +    stage_instance: InviteStageInstance | None = field(
```suggestion
    stage_instance: int | InviteStageInstance | None = field(
```

2022-08-01 00:53 UTC, i0bs commented on retux/client/resources/invite.py
> +    """stage instance data if there is a public Stage instance in the Stage channel this invite is for, if any. (deprecated)."""
```suggestion
    """Data of the instance if there is a public stage in the channel this invite is for. (deprecated)"""
```

2022-08-01 00:53 UTC, i0bs commented on retux/client/resources/invite.py
> +        Stage instance data if there is a public Stage instance in the Stage channel this invite is for, if any. (deprecated).
```suggestion
        Data of the instance if there is a public stage in the channel this invite is for. (deprecated)
```

2022-08-01 00:53 UTC, i0bs commented on retux/client/resources/invite.py
> +    # todo add this when added
```suggestion
    # TODO: Implement Guild Scheduled Event object
```

2022-08-01 20:56 UTC, i0bs requested changes

2022-08-01 20:56 UTC, i0bs commented on retux/client/resources/invite.py
> +    """A class object representing the Invite-target-types from discord."""
This needs documentation on the constants

Additionally, each constant requires a docstring of their own identical to what's written.

2022-08-01 20:56 UTC, i0bs commented on retux/client/resources/invite.py
> +    __________
```suggestion
    ----------
```

2022-08-01 20:56 UTC, i0bs commented on retux/client/resources/invite.py
> +    __________
```suggestion
    ----------
```

2022-08-01 20:56 UTC, i0bs commented on retux/client/resources/invite.py
> +        The topic of the Stage instance (1-120 characters).
```suggestion
        The topic of the stage instance in-between 1-120 characters.
```

2022-08-01 20:56 UTC, i0bs commented on retux/client/resources/invite.py
> +        The members speaking in the Stage.
```suggestion
        The members speaking in the stage.
```

2022-08-01 20:56 UTC, i0bs commented on retux/client/resources/invite.py
> +        The number of users in the Stage.
```suggestion
        The number of users in the stage.
```

2022-08-01 20:56 UTC, i0bs commented on retux/client/resources/invite.py
> +        The number of users speaking in the Stage.
```suggestion
        The number of users speaking in the stage.
```

2022-08-01 20:56 UTC, i0bs commented on retux/client/resources/invite.py
> +    """The members speaking in the Stage."""
```suggestion
    """The members speaking in the stage."""
```

2022-08-01 20:56 UTC, i0bs commented on retux/client/resources/invite.py
> +    """The number of users in the Stage."""
```suggestion
    """The number of users in the stage."""
```

2022-08-01 20:56 UTC, i0bs commented on retux/client/resources/invite.py
> +    "The number of users speaking in the Stage."
```suggestion
    "The number of users speaking in the stage."
```

2022-08-01 20:56 UTC, i0bs commented on retux/client/resources/invite.py
> +    "The topic of the Stage instance (1-120 characters)."
```suggestion
    "The topic of the stage instance in-between 1-120 characters."
```

2022-08-01 20:56 UTC, i0bs commented on retux/client/resources/invite.py
> +    """The expiration date of this invite, returned from the `GET /invites/<code>` endpoint when `with_expiration=True`."""
```suggestion
    """The expiration date of this invite, returned from the `Get Invites` endpoint when `with_expiration=True`."""
```

2022-08-01 20:58 UTC, EdVraz commented on retux/client/resources/invite.py
> +    """A class object representing the Invite-target-types from discord."""
https://discord.com/developers/docs/resources/invite#invite-object-invite-target-types

Discord doesn't provide a description so should I just imagine smth in the context?

2022-08-01 21:01 UTC, i0bs commented on retux/client/resources/invite.py
> +    """A class object representing the Invite-target-types from discord."""
Yeah, pretty much, that's how a lot of the enumerables have been documented so far

2022-08-06 10:17 UTC, i0bs requested changes

2022-08-06 10:17 UTC, i0bs commented on retux/client/resources/invite.py
> +    A class object representing the Invite-target-types from discord.
```suggestion
    Represents the targeted types of invites from Discord.
```

2022-08-06 10:17 UTC, i0bs commented on retux/client/resources/invite.py
> +        The invite targets  an embedded application.
```suggestion
        The invite targets an embedded application.
```

2022-08-08 12:18 UTC, i0bs approved these changes
LGTM, thank you for contributing to retux!

2022-08-08 12:18 UTC, merged