feat: implement `Image` object
retuxteam/retux pull request #46
Opened 2022-08-05 19:49 UTC by Dworv

This PR conveniently implements the `Image` object designed for ease of use with attrs. It features a dynamic converter function that allow for easily providing a path within `cdn.discordapp`.

2022-08-06 04:26 UTC, Dworv commented
This is ready now.

2022-08-06 10:16 UTC, i0bs requested changes

2022-08-06 10:16 UTC, i0bs commented on retux/client/resources/abc.py
> +        meant for endpoints that need a hash.
```suggestion
        meant for endpoints that need a hash.
        
        Please note that the naming of this method, `_c`
        does not reflect the same serialisation methods
        or strategies as `Serialisable._c()`.
```

2022-08-06 10:16 UTC, i0bs commented on retux/client/resources/abc.py
> +    """Internal use only. The endpoint of the image."""
```suggestion
    """The endpoint of the image."""
```

2022-08-06 10:16 UTC, i0bs commented on retux/client/resources/abc.py
> +    Internal use only. The needed variables aside
```suggestion
    The needed variables aside 
```

2022-08-08 12:20 UTC, i0bs approved these changes
LGTM, thanks for adding the clarification on the method.

2022-08-08 12:20 UTC, merged